### ISSUE TITLE
List index error when splitting and stripping line

### ISSUE THREAD

**Issue by NicholasPCole** [NicholasPCole/ping-logger#1]
Occasionally I'll get an email from cron that the script encountered this error:

    Traceback (most recent call last):
      File "/home/nicholas/scripts/ping-logger.py", line 86, in <module>
        point = convert_to_point(line)
      File "/home/nicholas/scripts/ping-logger.py", line 55, in convert_to_point
        pings = line.split(':')[1].lstrip().split(' ')
    IndexError: list index out of range

The traceback refers to these lines:

1. https://github.com/NicholasPCole/ping-logger/blob/d3bda42ea9cfd409a1abfd26ed11ff3fb4ae7d9b/ping-logger.py#L68
2. https://github.com/NicholasPCole/ping-logger/blob/d3bda42ea9cfd409a1abfd26ed11ff3fb4ae7d9b/ping-logger.py#L37

I need to set up some logging to capture what the variables are at that time to cause the error.

**Comment by NicholasPCole** [comment]
Rejecting - I've not seen this issue in some time and have made a few changes to the code since this revision.
